### ISSUE TITLE
unix <2.9 bounds is probably wrong

### ISSUE THREAD

**Issue by phadej** [judah/haskeline#129]
As `unix-2.8` is not yet on the horizon

**Comment by judah** [comment]
Thank you for calling this out.  There's some context for why it was bumped here:
https://gitlab.haskell.org/ghc/ghc/issues/15042
Taking a closer lookthe version *is* 2.8 upstream in the upstream unix repo HEAD and in GHC HEAD, but not in ghc-8.8 or in the pending ghc-8.10.

Looking at the changelog, it doesn't seem like any of the new changes would affect Haskeline.  I think it's simpler to leave it alone for now.  When unix-2.9 gets released, in the unlikely event that it breaks old Haskeline versions we can go back and make new package revisions for them on Hackage.  I'll leave this ticket open in the meantime.
