### ISSUE TITLE
haskeline-0.8.0.1 not on hackage, yet ghc-8.10.2 ships with it.

### ISSUE THREAD

**Issue by angerman** [judah/haskeline#144]
ghc-8.10.2 ships with haskeline-0.8.0.1 (https://downloads.haskell.org/~ghc/8.10.2/docs/html/users_guide/8.10.2-notes.html#included-libraries), however the most recent version on hackage as of today is 0.8.0.0 (https://hackage.haskell.org/package/haskeline).

Can this be rectified? Thanks!

/cc @bgamari :-/

**Comment by bgamari** [comment]
FWIW, 8.10.2 shipped with 463fc49d17bfab846cceba48bccc02ef285e6cba.

**Comment by judah** [comment]
Apologies for the oversight. I've released haskeline-0.8.0.1 at that commit.
