### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [judah/haskeline#165]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

**Comment by judah** [comment]
Hi, I wasn't able to get this working yet due to issues with dependencies. `haskeline` depends on the `exceptions` package which depends on `mtl`. However `mtl` currently doesn't have a version that's compatible with `transformers-0.6`:
https://hackage.haskell.org/package/mtl-2.2.2

I tried forcing the versions and got a compile error:
```
mtl       > /private/var/folders/dk/xxrqcv1n5_5_gzkyzc94r5_80000gn/T/stack-6ea93c2973aeaaa7/mtl-2.2.2/Control/Monad/Cont/Class.hs:58:1: error:
mtl       >     Could not load module ‘Control.Monad.Trans.Error’
mtl       >     It is a member of the hidden package ‘transformers-0.5.5.0’.
mtl       >     Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
mtl       >     Use -v to see a list of the files searched for.
mtl       >    |
mtl       > 58 | import Control.Monad.Trans.Error as Error
mtl       >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
@judah Thanks for looking into this. See https://github.com/haskell/mtl/issues/88 for the progress regarding `mtl`.

**Comment by sjakobi** [comment]
mtl-2.3 has been released. I can already build the library with `--allow-newer`, so bumping the bounds might be sufficient.

**Comment by sjakobi** [comment]
Ping @judah! :)

**Comment by sjakobi** [comment]
Another ping, @judah!

This issue is a bit more urgent now that `mtl-2.3.1` has been released.

**Comment by andreasabel** [comment]
Presumably fixed by:
- #173
