### ISSUE TITLE
Lower cabal requirement to 1.10

### ISSUE THREAD

**Issue by neothemachine** [judah/haskeline#17]
Between haskeline 0.7.1.0 and 0.7.1.2 you raised the required cabal version from 1.8 to 1.16, which by the way would totally require at least a minor version bump. Seeing that you only used the default-* features it would be enough to require cabal 1.10, since this is when that feature was introduced. The reason I ask for that is of course compatibility. Currently, a travis build of mine unnecessarily fails due to this: https://travis-ci.org/neothemachine/scion-class-browser/jobs/46119820 Lowering the bound makes it work: https://travis-ci.org/neothemachine/haskeline/jobs/46123976 It would be nice if the cabal bound could be lowered, at least to 1.14 in case you don't want to go down to 1.10. Thanks!

**Comment by hvr** [comment]
just noticed there's the  #15 PR to address this

**Comment by neothemachine** [comment]
Whoops, good to know. Now we just need to wait...

**Comment by judah** [comment]
Done in haskeline-7.2.0.
