### ISSUE TITLE
Odd behaviour with ANSI escapes in prompt

### ISSUE THREAD

**Issue by erikd** [judah/haskeline#44]
I'm seeing this in GHCi, but I assume its haskeline problem. Please correct me if I'm wrong on that.

I've noticed this minor annoyance for a while but didn't really explore it until now. I was going to do this bug report as an interpretive dance, but i decided an animated GIF was easier.

![ghci-prompt](https://cloud.githubusercontent.com/assets/307277/18332653/b50a3f34-75ab-11e6-84a2-e4271a8f1ff5.gif)

It seems that if the prompt string has non-printable characters recalling a previous multi line expression, followed by the down arrow key leaves the prompt in a strange state. Hopefully that will be obvious from the GIF. The prompt I'm using is:
```
:set prompt "\ESC[1;32mλ> \ESC[m"
```

**Comment by erikd** [comment]
@judah Hoping its really obvious where this problem is. If not, I'll dive in and have a look.

**Comment by judah** [comment]
The feature is documented here:
https://github.com/judah/haskeline/wiki/ControlSequencesInPrompt

Specifically, you need to add "\STX" to the end of each escape sequence, or else haskeline won't know the correct width of the prompt.  See that page for some examples.

Let me know whether that works for you.

**Comment by erikd** [comment]
Close, but still not quite right. Using `set prompt "\ESC[1;32mλ>\ESC[m \STX"` with the example before, using up arrow to recall the previous multiline expression, followed by down arrow leaves me with no prompt at all. I tied replacing the `λ` with something plain ASCII but that didn't help either.

**Comment by judah** [comment]
You need the "\STX" before the lambda too.  It should wrap the individual escape subsequences of the prompt.  Something like "\ESC[1;32m\STXλ> \ESC[m\STX"

**Comment by erikd** [comment]
That's got it!! :100:

**Comment by erikd** [comment]
Wonder if it might be worth checking the prompt at startup and printing an informational message on how to improve it.
