### ISSUE TITLE
upstream the win32 console text support to GHC

### ISSUE THREAD

**Issue by jmn** [judah/haskeline#47]
There's a bunch of issues on GHC's Trac regarding hPutChar crashing on Win32 - which seems to have been solved in Haskeline. Is there any possibility of upstreaming the code in Haskeline to GHC?

**Comment by judah** [comment]
Can you post a link to those GHC issues?  I did a quick search but wasn't sure which one(s) you were referring to.

**Comment by jmn** [comment]
- https://ghc.haskell.org/trac/ghc/ticket/4471
- https://ghc.haskell.org/trac/ghc/ticket/8118
- https://ghc.haskell.org/trac/ghc/ticket/10542

**Comment by DemiMarie** [comment]
The reason these are not issues in Haskeline is because it uses `WriteConsoleW`, which is the *only* correct way to write to a Windows console.

**Comment by judah** [comment]
Closing since, as mentioned above, these issues don't appear to be related specifically to Haskeline, and/or appear to be fixed upstream; e.g. ghc:
https://ghc.haskell.org/trac/ghc/ticket/4471#comment:29
