### ISSUE TITLE
http://trac.haskell.org/haskeline is down

### ISSUE THREAD

**Issue by wizzup** [judah/haskeline#71]
http://trac.haskell.org/haskeline

**Comment by judah** [comment]
Thank you for the report.  This was fixed in #70 by switching all links to GitHub, since `trac.haskell.org` is permanently shut down.  I've released `haskeline-0.7.4.1` which contains the updated link.

**Comment by wizzup** [comment]
Yo miss one spot.

![2017-12-02-195453_814x213_scrot](https://user-images.githubusercontent.com/342500/33515838-bfd69b54-d79a-11e7-99ba-4a9b34a379d0.png)

**Comment by judah** [comment]
Fixed, thanks for the catch!  I did a `git grep` and found a few more references, fixed in #73.
