### ISSUE TITLE
.haskeline doesn't seem to get picked up

### ISSUE THREAD

**Issue by buggymcbugfix** [judah/haskeline#98]
I have the following dotfile:
```
$ cat ~/.haskeline
historyDuplicates: IgnoreConsecutive
```
However running `stack ghci` my settings don't seem to get picked up. I'm on macOS 10.13.6. Any ideas?

**Comment by judah** [comment]
Hm, I just tried that and it worked for me.  A few thoughts:

- Do you see the same behavior with other options (for example, `completionType` or `editMode`?
- `IgnoreConsecutive` won't delete any duplicate entries that already exist, so it may just not be acting like you'd expect.  Does `IgnoreAll` work better for you?
- What OS and version of GHC are you using?

**Comment by buggymcbugfix** [comment]
Ah, thank you, I didn't realise that this doesn't work on existing entries!
